# List

In [ ]:

fruits =["apple","banana","cherry",1,2,3]


In [9]:
'''print(fruits)
type(fruits)
fruits[1:5]
fruits.append("orange")
fruits[2]="grape"'''
print(fruits)

['apple', 'banana', 'grape', 1, 2, 3, 'orange']


# Tuples

In [2]:
t=(1,2,3,"a","b")

In [6]:
t+=(1,3)
print(t)
t.count(1)

(1, 2, 3, 'a', 'b', 1, 3, 1, 3)


3

# Sets
Like list but can't add same values again

In [11]:
numbers={1,2,3,4,5}
numbers.add(6)
print(numbers)

{1, 2, 3, 4, 5, 6}


In [19]:
numbers.add(6)
numbers.remove(2)
print(numbers)

{1, 3, 4, 5, 6}


# Dictionary

In [20]:
dict={"A": 1, "B": 2, "C": 3}
print(dict)

{'A': 1, 'B': 2, 'C': 3}


In [26]:
#dict.values()
for key,value in dict.items():
    print(key,value,end="\n------\n",sep=":")

A:1
------
B:2
------
C:3
------


# Numpy

In [4]:
import numpy as np     
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(a[0,0:])

[1 2 3]


In [20]:
a.reshape(3,3)
a.shape

(3, 3)