# List

In [ ]:

fruits =["apple","banana","cherry",1,2,3]


In [9]:
'''print(fruits)
type(fruits)
fruits[1:5]
fruits.append("orange")
fruits[2]="grape"'''
print(fruits)

['apple', 'banana', 'grape', 1, 2, 3, 'orange']


# Tuples

In [2]:
t=(1,2,3,"a","b")

In [6]:
t+=(1,3)
print(t)
t.count(1)

(1, 2, 3, 'a', 'b', 1, 3, 1, 3)


3

# Sets
Like list but can't add same values again

In [11]:
numbers={1,2,3,4,5}
numbers.add(6)
print(numbers)

{1, 2, 3, 4, 5, 6}


In [19]:
numbers.add(6)
numbers.remove(2)
print(numbers)

{1, 3, 4, 5, 6}


# Dictionary

In [20]:
dict={"A": 1, "B": 2, "C": 3}
print(dict)

{'A': 1, 'B': 2, 'C': 3}


In [26]:
#dict.values()
for key,value in dict.items():
    print(key,value,end="\n------\n",sep=":")

A:1
------
B:2
------
C:3
------


# Numpy

In [4]:
import numpy as np     
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(a[0,0:])

[1 2 3]


In [21]:
a.reshape(3,3)
a.shape

(3, 3)

# Broadcasting

In [33]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr+10
print(arr)
print(np.median(arr))
print(np.sum(arr))
print(np.mean(arr))
#exp, log,sin,,cos,tan
#min,median,sum

[1 2 3 4 5]
3.0
15
3.0


# Pandas - 1D series and 2D Dataframes

In [36]:
import pandas as pd
sr=pd.Series([1,2,3,4,5])
print(sr)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [52]:
import pandas as pd
data={"Name": ["Alice", "Bob", "Charlie"],
      "Age": [25, 30, 35]}
df=pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


In [53]:
df.iloc[0:3]
df.loc[2,"Name"]

'Charlie'

In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv("IRIS.csv")
print(df.head())

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
