# List

In [ ]:

fruits =["apple","banana","cherry",1,2,3]


In [9]:
'''print(fruits)
type(fruits)
fruits[1:5]
fruits.append("orange")
fruits[2]="grape"'''
print(fruits)

['apple', 'banana', 'grape', 1, 2, 3, 'orange']


# Tuples

In [2]:
t=(1,2,3,"a","b")

In [6]:
t+=(1,3)
print(t)
t.count(1)

(1, 2, 3, 'a', 'b', 1, 3, 1, 3)


3

# Sets
Like list but can't add same values again

In [11]:
numbers={1,2,3,4,5}
numbers.add(6)
print(numbers)

{1, 2, 3, 4, 5, 6}


In [19]:
numbers.add(6)
numbers.remove(2)
print(numbers)

{1, 3, 4, 5, 6}


# Dictionary

In [20]:
dict={"A": 1, "B": 2, "C": 3}
print(dict)

{'A': 1, 'B': 2, 'C': 3}


In [26]:
#dict.values()
for key,value in dict.items():
    print(key,value,end="\n------\n",sep=":")

A:1
------
B:2
------
C:3
------


# Numpy

In [4]:
import numpy as np     
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(a[0,0:])

[1 2 3]


In [21]:
a.reshape(3,3)
a.shape

(3, 3)

# Broadcasting

In [33]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr+10
print(arr)
print(np.median(arr))
print(np.sum(arr))
print(np.mean(arr))
#exp, log,sin,,cos,tan
#min,median,sum

[1 2 3 4 5]
3.0
15
3.0


# Pandas - 1D series and 2D Dataframes

In [36]:
import pandas as pd
sr=pd.Series([1,2,3,4,5])
print(sr)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [52]:
import pandas as pd
data={"Name": ["Alice", "Bob", "Charlie"],
      "Age": [25, 30, 35]}
df=pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


In [53]:
df.iloc[0:3]
df.loc[2,"Name"]

'Charlie'

In [25]:
import numpy as np
import pandas as pd
df=pd.read_csv("IRIS.csv")
#df.head() -First 5 rows
#df.tail() -Last 5 rows
#np.shape(df) - Size of the dataframe()
#df.columns - Column names
#df.describe() - Statistical summary
#df.size - Total number of elements
#df.dtypes - Data types of each column

In [29]:
print(df.duplicated().sum())

0


In [31]:
df.drop_duplicates(inplace=True)

In [33]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [35]:
df.petal_length.unique()
df.petal_length.replace({6:6.1},inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_35244\1039017049.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.petal_length.replace({6:6.1},inplace=True)


0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ... 
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 147, dtype: float64